# Generated by Django 5.2.6 on 2025-09-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_birth_date_customuser_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_type',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('TI', 'Tarjeta de identidad'), ('PAS', 'Pasaporte'), ('NIT', 'NIT'), ('PEP', 'Permiso especial de permanencia')], max_length=5, null=True, verbose_name='Tipo de identificación'),
        ),
    ]
