# Generated by Django 5.2.6 on 2025-09-23 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='requester_office_text',
            field=models.CharField(blank=True, max_length=150, verbose_name='Oficina que solicita'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_assigned', to='oficinas.office', verbose_name='Oficina asignada'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='Descripción del servicio'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='equipment_code',
            field=models.CharField(blank=True, max_length=120, verbose_name='Código del equipo'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Muy baja'), (2, 'Baja'), (3, 'Media'), (4, 'Alta'), (5, 'Urgente')], default=3, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='requester_name',
            field=models.CharField(max_length=150, verbose_name='Nombre del solicitante'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='requester_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_requested', to='oficinas.office', verbose_name='Oficina que solicita (catálogo)'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('ASSIGNED', 'Asignado'), ('IN_PROGRESS', 'En curso'), ('PENDING_SUPPLIES', 'Pendiente por insumos'), ('COMPLETED', 'Completado')], default='DRAFT', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_supervised', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Técnico'),
        ),
    ]
